### ISSUE TITLE
Geographic error?

### ISSUE THREAD

**Issue by boristim66** [nextstrain/fauna#100]
https://github.com/nextstrain/fauna/blob/master/source-data/geo_synonyms.tsv:
110: Dnipro	Bangladesh	Bangladesh	Bangladesh

Is is a joke? I think it is a new name of Dnepropetrovsk, Ukraine :)

**Comment by tsibley** [comment]
Looks like this mistake was [introduced](https://github.com/nextstrain/fauna/commit/29df1b1b686d95a6b3e76dab7fa926a2b6ac8cef#diff-8611720e569f2560f622006c368b7214R92) over three years during a large data reformatting commit. It was [correct up to that point](https://github.com/nextstrain/fauna/commit/29df1b1b686d95a6b3e76dab7fa926a2b6ac8cef#diff-8611720e569f2560f622006c368b7214L1371).

**Comment by trvrb** [comment]
Thanks for the catch @boristim66! These geo synonyms are obviously pretty ad hoc.
