### ISSUE TITLE
Pylint alerts corrections as part of an intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [nextstrain/fauna#168]
### Context
Pylint alerts are correlated with tendency to bugs and harder maintenance.
I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/) alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).

In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

Your repository is expected to benefit from the interventions.
I'm asking for your approval for conducting an intervention in your repository.

May I do the interventions?

### Description
I will go over the choosen alerts, fix them and submit a PR.
Most chenges are small and easy to review.

See examples of done interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

### Examples

You can see the [planed interventions](https://github.com/evidencebp/pylint-intervention/tree/main/interventions/candidates/nextstrain_fauna_interventions_October_06_2024.csv)

### Possible solution
I'll fix the alerts.

**Comment by victorlin** [comment]
Hi @evidencebp thank you for filling out the issue form. We do not plan to enforce Pylint in this repository any time soon, and even if we do, we would rather use a custom set of rules picked by the Nextstrain team.
