### ISSUE TITLE
Use custom runtime

### ISSUE THREAD

**Issue by victorlin** [nextstrain/fauna#170]
_follow-up to https://github.com/nextstrain/fauna/issues/169#issuecomment-2492503576_

## Context

Fauna is currently available through the Nextstrain managed runtimes (docker-base, conda-base). There are a couple of reasons to consider its removal from those:

1. It is only used for seasonal-flu and avian-flu and there are no plans to incorporate new pathogens during the expansion of Nextstrain's core pathogens.
2. With the current usage, there is no reason to update the code and [dependency version constraints](https://github.com/nextstrain/fauna/blob/d632af090c19f2601d99223a6c23047858a82a15/requirements.txt). This goes against the grain of the base runtimes, which are frequently kept up to date with latest versions of tools and their dependencies. At some point down the road, dependencies may fail to resolve entirely (e.g. if Fauna is pinned to Pandas v1 and Augur stops supporting that version).

## Possible solutions

1. Define, [publish](https://github.com/victorlin/nextstrain-custom-docker), and use a custom Docker image that extends `nextstrain/base`.
2. Define and use a custom Conda environment that extends `nextstrain::nextstrain-base`.

Both of these could be pursued to allow flexibility for users.

**Comment by victorlin** [comment]
This should be considered under a broader proposal: https://github.com/nextstrain/public/issues/7

**Comment by joverlee521** [comment]
Fauna is not included in the Nextstrain conda runtime (past discussion on this in https://github.com/nextstrain/conda-base/issues/3), which is even more reason to just use a custom Docker image for fauna.

**Comment by jameshadfield** [comment]
> Define, [publish](https://github.com/victorlin/nextstrain-custom-docker), and use a custom Docker image that extends nextstrain/base.

> just use a custom Docker image for fauna

In this specific case, if the avian-flu ingest workflow is run in the docker/aws runtimes, i.e. starting within the canonical nextstrain docker container, and [a rule needs `fauna`](https://github.com/nextstrain/avian-flu/blob/0780396e4ed19bb21d8599165baac128ed7280b9/ingest/rules/ingest_fauna.smk#L21), what's the plan to do this? Docker-in-docker is [discouraged](https://stackoverflow.com/a/33003273). Running multiple sibling containers and communicating between them is going to require a bunch of work to enable. 

If we don't have a plan then I think this issue should be closed (and https://github.com/nextstrain/public/issues/7) and leave it all for workflows-as-programs buildpacks, when we get to that.

**Comment by victorlin** [comment]
No plan. The current workaround, as noted in nextstrain/public#7:

> The ad-hoc approach of defining/creating custom runtimes by extending a base (examples: [1](https://github.com/nextstrain/ncov-ingest/blob/c1af4b7e5e956c92e6bac224d6c3d87cf758a46f/Dockerfile), [2](https://github.com/victorlin/nextstrain-custom-docker), [3](https://github.com/nextstrain/zika-tutorial/blob/1ab0e32bf679727a961cd90f65741aeff5ab99a9/envs/nextstrain.yaml)) has been used internally to some extent. The process is quite involved and not ideal for users at large.

After our recent dev discussion, I also think it's appropriate to close these issues for now.
