### ISSUE TITLE
Error when updating Zika citations or locations

### ISSUE THREAD

**Issue by trvrb** [nextstrain/fauna#39]
I'm getting an error when I try to update Zika citation information or location information, either

    python vdb/zika_update.py -db vdb -v zika --update_citations
    python vdb/zika_update.py -db vdb -v zika --update_locations

I get:

```
Traceback (most recent call last):
  File "vdb/zika_update.py", line 13, in <module>
    connVDB.update(**args.__dict__)
  File "/Users/trvrb/Documents/src/fauna/vdb/update.py", line 20, in update
    self.update_locations(**kwargs)
  File "/Users/trvrb/Documents/src/fauna/vdb/update.py", line 67, in update_locations
    self.upload_to_rethinkdb(self.database, self.viruses_table, viruses, overwrite=True)
  File "/Users/trvrb/Documents/src/fauna/vdb/upload.py", line 500, in upload_to_rethinkdb
    raise Exception("Couldn't insert new documents into database", database + "." + table)
Exception: ("Couldn't insert new documents into database", 'vdb.zika_viruses')
```

However, it looks like it's actually updating. @chacalle, sorry about this, but is there an obvious solution? I should be getting more familiar with the codebase.

**Comment by chacalle** [comment]
Sorry about this. Was missing a kwargs when passing to self.upload_to_rethinkdb. This should be fixed now. And you're right that it was still updating the actual documents, was failing when trying to update the timestamp. I moved self.update_timestamp out of that try except section.

**Comment by trvrb** [comment]
Thanks so much @chacalle. I really appreciate this. `--update_locations` is now working, however `python vdb/zika_update.py -db vdb -v zika --update_citations` is throwing an error. 

`update_timestamp` is called with `update_timestamp(table, document_changes, **kwargs)`: https://github.com/nextstrain/fauna/blob/master/vdb/upload.py#L501

but it expects `update_timestamp(self, table, document_changes, index, **kwargs)`: https://github.com/nextstrain/fauna/blob/master/vdb/upload.py#L510

**Comment by chacalle** [comment]
No problem, thanks for catching that. I think this works now.

**Comment by trvrb** [comment]
This is working now. Thanks so much @chacalle.
