### ISSUE TITLE
database dump

### ISSUE THREAD

**Issue by viehwegerlib** [nextstrain/fauna#59]
Dear all,

Is it possible to get a copy of a nextstrain database dump (e.g. in JSON)? Or is this problematic for proprietary reasons?

Best and thanks,
Adrian

**Comment by trvrb** [comment]
There are issues with data sharing that, unfortunately, prevent this to some degree. For example, our flu data comes from [gisaid.org](http://gisaid.org), where there is a fairly strict requirement that sequences not be further shared. However, depending on your virus of interest, reconstructing the database should be straight forward. We've maintained notes on this here:

* https://github.com/nextstrain/fauna/blob/master/ZIKA.md
* https://github.com/nextstrain/fauna/blob/master/EBOLA.md
* https://github.com/nextstrain/fauna/blob/master/FLU.md

**Comment by viehwegerlib** [comment]
So there are restrictions that apply to all collections, i.e. Ebola, Zika etc.?

Thank you for the links!

**Comment by trvrb** [comment]
@viehwegerlib ---

Sorry to be slow. We are purposely not rehosting data at the moment. In addition to flu, much of the Ebola and Zika data came from sources that had explicit "pre-publication disclaimers"(like [here](http://evident-project.eu/newsevents/ebov-sequences/) and [here](https://github.com/zibraproject/zibraproject.github.io/tree/master/data/consensus)). We're working on a solution here in which sequences could be flagged with something like a license. But in the meantime, I'm sorry but we can't share raw sequence data.
