### ISSUE TITLE
error with npm run chateau

### ISSUE THREAD

**Issue by j3tkd** [nextstrain/fauna#60]
I got an error from 'npm run chateau' and to mention that './chateau/bin/chateau' fails in your system. Any advice?

Justin

**Comment by robynhall** [comment]
I am getting the same error using Windows 10 64-bit. 
![error chateau](https://cloud.githubusercontent.com/assets/28820223/26273438/bda38660-3d73-11e7-813c-22c6e29244ce.JPG)

**Comment by jameshadfield** [comment]
I believe these errors are due to windows (which none of us use) vs unix(-like). @barneypotter24 any ideas?

**Comment by trvrb** [comment]
@j3tkd and @robynhall ---

The file in question is https://github.com/neumino/chateau/blob/master/bin/chateau. This is a node file. You likely need to install node on your system.
