### ISSUE TITLE
Fix dengue author info

### ISSUE THREAD

**Issue by trvrb** [nextstrain/fauna#69]
`vdb/dengue_sequences` has authors in format of `Corwin et al.`, `Dewi et al.`, etc... Zika, Ebola, etc... have authors in format of `Mlakar et al`. The presence of the `.` is causing some downstream issues. Not high priority, but would be good to fix.

**Comment by joverlee521** [comment]
Closing this issue since we are no longer processing dengue sequences through fauna.
