### ISSUE TITLE
What should the environment variables RETHINK_HOST and RETHINK_AUTH_KEY be set to? 

### ISSUE THREAD

**Issue by samyuktr** [nextstrain/fauna#70]
Trying to install fauna. README not clear on how to set the variables. Without setting the variables "npm run chateau-local" giving errors.

**Comment by trvrb** [comment]
@samyuktr ---

Sorry this wasn't clear. These environment variables will depend on your own RethinkDB instance. You can run a local version of RethinkDB. I've added some documentation here: https://github.com/nextstrain/fauna#environment-variables.
