### ISSUE TITLE
Higher resolution sampling date available for Zika strain HN16

### ISSUE THREAD

**Issue by alliblk** [nextstrain/fauna#71]
Murray et al have a whole Zika genome, strain HN16, GenBank accession KY328289, for which collection date is listed as May-2016. The initial sequence submission was actually of a partial sequence with accession KX928077 (this is the accession listed in the paper). That GenBank entry has the full collection date as May-16-2016. The paper describes collection as occurring in mid-May, so I think that the full collection date is correct. We should replace the May-2016 date with the May-16-2016 date in Fauna.

**Comment by trvrb** [comment]
Thanks @alliblk!
