### ISSUE TITLE
chateau submodule error

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/fauna#73]
branch: `master` commit: 2f5453b560b99a8194a17c4e0771eafe1f8f8787
```
$ git submodule update --recursive
Username for 'https://github.com': ***
Password for 'https://***@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/blab/chateau/' not found
Unable to fetch in submodule path 'chateau'
```

**Comment by trvrb** [comment]
I think you have to reinitialize submodules. I updated the `.gitmodules` file: https://github.com/nextstrain/fauna/blob/master/.gitmodules in this commit: 4cfd65630b0a5bd7fbcdbbf1ba7e250977957d5e. I think this is `git submodule update --init`.

**Comment by jameshadfield** [comment]
I've tried that, I believe the underlying problem is this: `fatal: repository 'https://github.com/blab/chateau/' not found`

**Comment by jameshadfield** [comment]
to fix, run:
```
git submodule sync
git submodule update --init --recursive
```
