### ISSUE TITLE
Migrate to pandas 0.17

### ISSUE THREAD

**Issue by stevenweaver** [nextstrain/fauna#87]
Dear @nextstrain,

Currently, fauna states the following in its `requirements.txt` file 

```
pandas >=0.16.2, ==0.16.*  
```

However, if one were to use the same virtual environment for augur, there is a dependency conflict for treetime. 

```
treetime 0.4.0 has requirement pandas>=0.17.1, but you'll have pandas 0.16.2 which is incompatible.
```

I'm working around this by removing the pandas requirement in fauna, but thought that making an issue may be appropriate. 

Best,
Steven

**Comment by tsibley** [comment]
Hi @stevenweaver, thanks for opening this issue. We should resolve this conflict one way or another. A quick question for you: are you using modular augur (the `augur <command>` CLI) or the augur code under `base/`?

**Comment by tsibley** [comment]
Also, for what it's worth, I suspect that fauna is just fine with a newer pandas. It's pinned to 0.16.2 because pandas documented breaking changes in 0.17 but 0.16.2 is known good for fauna. If someone verifies that the breaking changes in 0.17 don't break fauna, then we could upgrade the requirement.

Ideally we'd actually verify not 0.17 but the latest pandas so that we'd get back on the current version train. :-)

**Comment by stevenweaver** [comment]
Dear @tsibley, 

Ok, once fauna is fully running, I can report whether I run into issues with the new pandas version.
Also, I'm using modular augur. I use `Arch Linux`, I prefer to live dangerously. 

Best,
Steven

**Comment by tsibley** [comment]
Ah, since you're using modular augur, which is Python 3, I'm surprised that you're installing fauna, which is Python 2, into the same virtualenv. Anyway, it'd be great to hear back about issues or non-issues. Thanks!

>  I use Arch Linux, so that should tell you that I prefer to live dangerously.

It does! 😂

**Comment by trvrb** [comment]
Thanks for letting us know about this @stevenweaver. I just confirmed that pandas 0.17.1 works for fauna (just used in a small bit of the code base). I'm going through now and seeing if this upgrade can be made elsewhere.

**Comment by stevenweaver** [comment]
Thank you @trvrb!
