### ISSUE TITLE
Fauna installation fails for some users who don't run `npm install` inside of `/chateau`

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/fauna#95]
@ebaberga and I were just troubleshooting a `fauna` install.

She was getting the following error when running `npm run chateau` from the `fauna` directory.
<img width="838" alt="Screen Shot 2019-07-15 at 1 35 34 PM" src="https://user-images.githubusercontent.com/11384464/61250004-76bbaa80-a70b-11e9-9194-4f6049075ada.png">

We couldn't get the server to run until she ran `cd chateau && npm install`. 

What would cause this? Why did this happen? I just did a re-install of fauna on Ubuntu and did not run into this issue.

**Comment by jameshadfield** [comment]
@kairstenfay @ebaberga can you please change the README for this? chateau is a submodule and has its own npm dependencies -- see https://github.com/nextstrain/chateau/blob/58fe2d308d0f50157d7148eab78be83cb53b65fb/package.json. 

Additional README modifications:
* after `git clone https://github.com/nextstrain/fauna.git` one needs to `cd fauna`

**Comment by kairstenfay** [comment]
Done with two new commits to master by @ebaberga .

This repo has some unusual restrictions on pushing branches and force-pushing which is why the changes were done via direct commits to master. Feel free to rebase as you see fit @jameshadfield .

**Comment by jameshadfield** [comment]
Thanks @ebaberga 🎉
