### ISSUE TITLE
fauna doesn't work with rethinkdb 2.4

### ISSUE THREAD

**Issue by rneher** [nextstrain/fauna#99]

**Comment by rneher** [comment]
the most recent version of rethinkdb (2.4.*) doesn't have an attribute `.connect` and fails.

**Comment by jstoja** [comment]
Hey @rneher.

What do you mean by "doesn't have an attribute `.connect` and fails`?
I cannot find any attribute being used in fauna, and the RethinkDB still documents a `.connect()` method (https://rethinkdb.com/api/python/connect/).

Could you elaborate?

Thanks

**Comment by lukelima** [comment]
Hello @rneher ! Could you describe a little more about this issue ?

**Comment by joverlee521** [comment]
Resolved by https://github.com/nextstrain/fauna/pull/104
